# Generated by Django 4.2.7 on 2025-03-06 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_alter_rating_unique_together_alter_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('recipe', 'user', 'session_key')},
        ),
    ]
