# Generated by Django 4.2.7 on 2025-04-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rating_session_key_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_instructions',
            field=models.TextField(blank=True, help_text='Подробное описание шагов приготовления', verbose_name='Процесс приготовления'),
        ),
    ]
